Fix testing
gnocchixyz/python-gnocchiclient pull request #111
Opened 2020-09-09 23:48 UTC by tobias-urdin

2020-09-10 10:47 UTC, tobias-urdin commented
Need to investigate manually why test is hanging.

2020-09-10 11:22 UTC, jd approved these changes
LGTM

2020-09-10 11:22 UTC, jd commented on .mergify.yml
> +    - '#approved-reviews-by>=2'
maybe 1 is enough nowadays :)

2020-12-07 18:18 UTC, tobias-urdin commented
@jd this is OK, the failing test is from old travis-ci.org, the new ones passed

2020-12-07 19:31 UTC, jd requested changes
The CI is wrong for Mergify.

2020-12-07 19:31 UTC, jd commented on .mergify.yml
> +    - status-success=continuous-integration/travis-ci/pr
```suggestion
    - status-success=Travis CI - Pull Request
```

2020-12-07 19:31 UTC, jd commented on .mergify.yml
> +    - status-success=continuous-integration/travis-ci/pr
```suggestion
    - status-success=Travis CI - Pull Request
```

2020-12-07 19:39 UTC, tobias-urdin commented
Don't think so but we can try, the issue does not exist in gnocchi repo

2020-12-07 20:03 UTC, merged

2020-12-07 20:04 UTC, jd commented
> Don't think so but we can try, the issue does not exist in gnocchi repo

it does, nothing will get automerged until you fix it